spring:
  application:
    name: workflow

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: techpulseworkflowsecretkeytechpulseworkflowsecretkey
  expiration: 86400000
